### ISSUE TITLE
Epic 4: User Profile, Daily Logs, and Recipes (cont.)

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#111]
- [x] User profile update (Michael) #115 
- [x] Daily logs:
    - [x] Change the food input from dropdown select to search by text (Athena) #117 
    - [x] Display log page: display  (Tsion) #112
- [x] Recipes:
    - [x] More recipe pages (Bryce and Jalen) #121
    - [x] Add allergy and diet info to recipe (John) #119
- [x] Write AWS documentation (Athena) #116
