### ISSUE TITLE
 Display log page

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#112]
**Subtasks:**
 - [ ] User can view their logged information he/she submitted

> - [x]  Date
>  - [x]  Time
>  - [x]  Food
>  - [x]  Portion

**Test cases**
- [x] User can successfully view their log
- [x]  The viewable information can be seen from admin page as well

**Comment by Tsion-Tadesse** [comment]
Daily log successfully display daily log date, time, food and portions.
