### ISSUE TITLE
Fix User Profiles

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#115]
**Sub-tasks:**
- [x] User profile form should only be editable by the user in question
- [x] Metric unit option should convert height/weight between imperial and metric
- [x] Form should be in a table

**Test Cases**
- [x] User can't edit other users profiles, only their own
- [x] Changing Metric option changes between lb/kg, and feet/centimeters
- [x] Form is correctly displayed
