### ISSUE TITLE
Finish User Profile

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#133]
** Sub-tasks **
- [x] Update metric/imperial conversion
    - [x] "Metric preferred?" changed to "Use metric: "
    - [x] Checking/unchecking "use metric" immediately converts units and displays correct units in labels
- [x] Update profile form includes fields in user account model (email, first name, last name)

** Test cases **
- [x] Update form changes between metric/imperial units when checkbox selected
- [x] User can update email, first name, last name
