### ISSUE TITLE
Epic 5: User Profile, Daily Logs, and Recipes (cont.)

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#134]
- [x] User Profile #133 (Michael)
    - [x] Update metric/imperial conversion
    - [x] Update profile form includes fields in user account model (email, first name, last name)
- [x] Daily Logs #136 (Athena and Tsion)
    - [x] List
    - [x] Edit
    - [x] Delete
- [x] Recipes (Bryce and John)
    - [x] Recipe feature enhancement #138
- [x] Search
    - [x] Pagination of results #135 (Michael)
    - [x] Radio buttons (or dropdown selector) next to the search bar for determining whether you search foods or recipes #139 (Jalen)
