### ISSUE TITLE
Expand on daily logs

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#136]
**Subtasks**
- [x] Daily log list page
    - [x] Option to add a log
    - [x] Link to each daily log
    - [x] Option to delete each log
- [x] Daily log details page
    - [x] Date
    - [x] Option to delete daily log
    - [x] Display info of each meal log (time, foods, total nutrients)
    - [x] Option to edit each meal log
    - [x] Option to delete each meal log
    - [x] Display total nutrients for the day
- [x] Meal log edit page
    - [x] Edit date (changes to new or existing DailyLog)
    - [x] Edit time
    - [x] Edit food
    - [x] Edit portions
    - [x] Add food (creates meal food)

**Test cases**
- [x] Correct display for daily log list
- [x] Correct display for daily log details
- [x] Successfully edit meal log information
- [x] Successfully delete logs
