### ISSUE TITLE
Public user-created recipes search and view by other users feature

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#155]
**Sub-tasks**
- [x] RecipePreset model removed
- [x] Option on create/edit recipe pages to make a recipe public or private
- [x] Searching recipes searches for recipes created by current user and recipes flagged as public
- [x] Users not able to edit or delete other user's recipes

**Test cases**
- [x] Recipes can be made public
- [x] Searching recipes shows public recipes or recipes created by current user
- [x] User can view public recipes
- [x] User cannot edit/delete other people's recipes
