### ISSUE TITLE
Epic 6: database, search, UI, logs, recipes

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#156]
- Database
    - [x] Fix database values (John) (Nov 9) #160
    - [x] Ongoing: Add more foods to database (John) #162
- Recipes
    - [x] Polishing recipes (Bryce Nov 9) #158
- Search
    - [x] Public user-created recipes can be searched and viewed by other users (Michael) (Nov 9) #155
- Logs
    - [x] Finish log updating functionality (Athena) (Nov 9) #159 
- UI
    - [x] Add Pi-chart in nutrifact page to visualize nutrition fact (Tsion) (Nov 9) #157 
    - [x] Update/polish UI (Jalen) #163
