### ISSUE TITLE
Finish log update functionality

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#159]
**Subtasks**
- [x] Delete foods from log
    - [x] JavaScript to hide and disable "deleted" fields
    - [x] Backend disregards missing fields
    - [x] Do the same for log creation
- [x] Errors display properly for both log creation and update
    - [x] Future date/time not allowed
    - [x] Portions must be greater than zero

**Test cases**
- [x] Foods deleted successfully
- [x] Errors appear on appropriate fields
