### ISSUE TITLE
Bryce's tasks for Epic 7

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#176]
- Foods show a list of recipes which contain them as an ingredient
    - [x] In the nutrifacts view, include a list of public recipes and personally owned recipes which contain that food as an ingredient

- Recipe Cloning
    - [x] Have button in detail template to clone an existing recipe
    - [ ] Have functionality to clone an existing recipe
    - [x] If it's a public recipe, the resulting clone is a private recipe

- Recipe Form validation
    - [x] Validate so it doesn't create/update if the new version has two of the same ingredient
    - [x] Make it so that it isn't hard-coded which rows are cloned by the Add another Food button

- Personal Recipe List
    - [ ] Shows number of ingredients of each item
    - [x] Shows calories per serving of each item

- [x] Detail view's delete button should have an "are you sure?" popup
