### ISSUE TITLE
Incorporate recipes into logs

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#177]
**Subtasks**
- [x] Add recipes to log functionality:
    - [x] Rename MealFood to MealItem and add Recipe field (models, migrations, db)
    - [x] Add RecipeAutocomplete (views, urls)
        - [x] Only public recipes and recipes created by user
    - [x] Update get_total() for MealLog (models)
    - [x] Update LogForm (forms)
    - [x] Update LogCreate and LogUpdate (views)
    - [x] Update JavaScript (templates)
        - [x] Add and remove recipe fields
        - [x] Change from hardcoded rows to parentElement
- [x] When creating/editing log, must have either at least one food or at least one recipe (forms, clean())

**Test cases**
- [x] Successfully add recipe to log
- [x] Cannot have an empty log
