### ISSUE TITLE
Epic 7: Splitting views.py and miscellaneous improvements

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#178]
- [x] Quality of life changes to recipes and foods: (Bryce Nov16) #176

- [x] Incorporate recipes into logs: (Athena Nov16) #177

- [x] Recipe allergy/diet additions: (Michael Nov16) #179 

- [x] UI revisions/ and cropping (Jalen Nov16) #180

- [x] Add pie-chart in nutrifact page to visualize nutrition fact (Tsion) (Nov 16) #157 

- [x] Splitting views.py into three manageable pieces (finish before Wednesday the 11th)

- [x] Help work on issues brought up in comments and finish adding all remaining foods to database. (John) #188

**Comment by Vanasbry000** [comment]
Nutrition Helper Priorities from other group:
Bugs:
- [x] Recipe creation page should only be accessible to logged in users
- [x] Empty recipe search should return no results (Tsion)
- [x] 1.00 g in recipe creator should be changed to 1 unit
- [x] Deleting recipe from recipe list gives a forbidden error (Tsion) (fixed by Bryce)

CSS:
- [x] Signup page error messages shouldn’t be hard-to-see left-aligned black text
- [x] Create recipe page affects navbar font (fixed)
- [x] Update recipe page affects search bar (Tsion)
- [x] Add empty space under page content so it doesn’t look too abrupt
