### ISSUE TITLE
Recipe Allergy/Diet Additions

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#179]
**Sub-tasks**
- [x] Recipe can have multiple allergies or diets attached to it
- [x] Recipe search displays multiple allergies/diets correctly
- [x] Can filter searches based on allergy/diet
- [x] Search filter defaults to allergy/diet preferences attached to current user's profile

**Test cases**
- [x] User can add/remove multiple allergies and diets from recipes
- [x] Search results correctly display multiple allergies/diets
- [x] Selections to filter search results based on allergy/diet
- [x] Filter defaults to allergies and diets attached to the user's profile
