### ISSUE TITLE
EPIC 8: Homepage

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#201]
- [x] Graphing logs (Athena Nov 30) #202 
- [x] Stuff (Bryce Nov 30) #203 
- [x] Pi-chart modification and Add daily calorie intake goal form in user profile  (Tsion) #205 
- [x] Additional search functionality (Michael Nov 30) #204 
- [x] Homepage revamp (Tsion Nov 30) #206 
- [x] Front-end changes (Jalen) #207
- [x] Remove ability to access recipe page when not logged in (John) #182
