### ISSUE TITLE
Graphing logs

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#202]
**Subtasks**
- [x] Figure out AJAX with Django
- [x] Line graph showing consumption of nutrients for each day (Chart.js)
    - [x] Able to choose between multiple nutrients
    - [x] Able to choose time span of current week, month, or year
    - [x] Clicking on a marker takes you to detail page

**Test cases**
- [x] It'll work

**Extra subtasks that I might or might not get done**
- [x] Time span options include past 7 days or past 30 days
- Display the "goal range" on the graph (depends on completion of others' tasks)
- Unrelated to graph:
    - [x] Log create page: autofill current date and time
    - [x] Log detail page: add an "add meal" button that autofills date field
