### ISSUE TITLE
Bryce's tasks for Epic 8

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#203]
- Recipe Cloning
    - [x] Have the fields of the clone page initialize to the source recipe's values
    - [x] Button available from detail view

- Recipe Form
    - [x] Make it so that it isn't hard-coded which rows are cloned by the Add another Food button

- Personal Recipe List
    - [x] Shows most of the information that the recipe search results manages to show

- Foods show a list of recipes which contain them as an ingredient
    - [x] In the nutrifacts view, include a list of public recipes and personally owned recipes which contain that food as an ingredient
    - [x] Shows most of the information that the recipe search results manages to show
