### ISSUE TITLE
Additional search functionality

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#204]
**Sub-tasks**
- [x] Make column headers clickable in search recipe and search food to sort search results
- [x] Search filter for food and recipe to search for food with calories between two amounts
- [x] Search filter for recipe to search for recipe containing a specific food

**Test cases**
- [x] User can order the search results by clicking the column headers
- [x] User can input desired caloric range when searching food and recipes
- [x] User can search recipes that contain a specific food

**Comment by ghost** [comment]
I wasn't able to get the filter and sorting for recipe calories working. It will require changing the structure of recipes in the database I think.
