### ISSUE TITLE
Homepage revamp

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#206]
**Subtasks**
- [x] Remove “How it Works” page and add an updated version of that info (right now it's still about our prototype) to the homepage with our names and stuff

- [x] Add log and recipe button 
- [x]  Only visible when the user log in

- [x] Add links to and explanations of main features to homepage (logs, recipes)
- [x] Add signup/login form to the homepage if you aren’t signed in
    - [x] Easiest way: Add UserCreationForm to context and template, then a button/link that says something like "Already have an account? Sign in here" that takes you to the login page
