### ISSUE TITLE
epic 8 task (Jalen)

### ISSUE THREAD

**Issue by collegeStudent35632** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#207]
- [x] Re-color and/or re-arrange text fields that are difficult to see
- [x] Resolve more html/css bugs 
- [x] create and add favicon

**Comment by collegeStudent35632** [comment]
#212
