### ISSUE TITLE
Epic 9: Feature improvements

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#217]
- [x] Refine log graph/list page (Athena) #219 
- [x] Navigation bar update (Jalen) #208 
- [x] Continue fixing names in database (John) #220
- [x] Recipe pi chart and more (Bryce) #221 
- [x] User profile picture upload (Tsion) #216 
- [x] Homepage Revamp (Tsion) #206 
- [x] More search additions (Michael) #222
