### ISSUE TITLE
Refine log graph/list page

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#219]
**Subtasks**
- [x] Add calorie goal as line
- [x] Add average daily intake of selected nutrient for selected time period as line
- [x] Add legend for both where calorie goal only appears when "Calories" is selected
- [x] Only list logs for current month, can select past months

**Test cases**
- [x] Graph functions properly
- [x] Log list month selection works
