### ISSUE TITLE
More Search Additions

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#222]
**Sub-tasks**
- [x] Fix changing pages with recipe search filters
- [x] Ordering search results in descending order as well as ascending
- [x] Add ManyToMany field to Recipe model with Food using RecipeFood as 'through' model so Django knows about this relationship
- [x] Order recipe search by calories
- [x] Filter recipe search by calorie range
- [x] Change diet and allergy recipe filters to a dropdown menu with checkboxes
- [x] Change food search filter to allow for filtering for a range in any field, not just calories, and allow for multiple filters

**Test cases**
- [x] User can change pages after searching a recipe without resetting filters
- [x] User can click a column header in searches twice to filter in descending order
- [x] User can order recipe searches by calories
- [x] User can search recipes within a calorie range
- [x] Diet and allergy recipe search filters are dropdown menus with checkboxes
- [x] When searching foods, user can add additional search filters for certain nutrition facts and enter the desired ranges
