### ISSUE TITLE
Epic 10: Wrapping things up with the finishing touches

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#230]
- [x] HTML/CSS cleanup for logs & navbar (Athena) #232
- [x] Bryce #231
- [ ] Remove egg and broccoli and kit kat and other stuff that was added at the very start by hand instead of coming from the USDA database (???)
- [x] Homepage revamp cont.. and (recipe and profile CSS) #233 (Tsion)
- [x] Fix multiple food search filters (Michael) #235 
- [x] Add more food button in the create_recipe page and all subpages don't work (bug notice)
