### ISSUE TITLE
Bryce's tasks for epic 10

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#231]
- [x] Restore the functionality of the add ingredient button on the clone, the create, and the update pages
- [x] Remove cholesterol from the pie chart of the recipe page
- [ ] Remove hard codedness of the remove recipe button
- [x] If you own a recipe, have something in detail view that tells you if it's public vs private
- [x] Remove the pagination from the nutrifacts page
- [x] Add a nice background to the recipe list page
- [x] Add a thing to the recipe list page which says how many ingredients a recipe contains
