### ISSUE TITLE
HTML/CSS cleanup for logs & navbar

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#232]
**Subtasks**
- [x] Make HTML files for log pages extend from one base
- [x] Prettify log detail table
- [x] Change z-index of navbar so it always appears on top of other elements

**Test cases**
- [x] It'll look a little nicer
