### ISSUE TITLE
Epic 1: Function to track food intake

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#52]
As a user, I want to track my food intake so that I can build healthier eating habits in the long and short term.

- [x] Add user accounts (Michael)
    - [x] Login Page
    - [x] Logout Page
    - [x] Change Password Page
    - [x] Register Account Page
- [x] Finish adding all the foods to the database (John, Jalen)
- [x] Nutrition facts adjusting with portion size (Athena)
- [x] Build a page where the user can add information about their food intake (Tsion)
    - [x] Write HTML for daily intake page
    - [x] Function that allows user to record what, how much, and when they ate
- [x] Save user data and make it available for only that user to view (Bryce)
    - [x] Create model to contain user data
    - [x] Function that saves data to specific user
