### ISSUE TITLE
Epic 2: Build User Profile and Record User Consumption

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#68]
As a user, I want to record the consumption of multiple foods at the same time, either as meals or as recipes, so that I can have accurate logs without it being a chore. In addition, I want to be able to add my dietary preferences and allergies, so that I can be able to get ingredients of my choice. 

- [x] Allow user to add his/her dietary preferences/allergies in their profile (Michael Oct 12) #77 
- [x] Expand/modify meal logs -(Tsion Oct 12) #74 
    - [x] To be able to record meals -(Tsion Oct 12)
    - [x] Modify to make it user friendly  - (Tsion Oct 12)
- [x] Daily log and meal log model (Athena Oct 12) #73 
- [x] Recipe model (Bryce Oct 12) #75 
    - [x] User can create recipes with multiple foods
    - [x] Recipes are specific to user and they have any number of foods and portions of each food
- [x] Allow user to search public recipes (Jalen Oct 12)
    - [x] Implement new recipe table into the database
- [x] Get food variants added to database (John Oct 12) #37

**Comment by sjiang1** [comment]
@Vanasbry000 

This task does not have an issue:
> Allow user to add his/her allergies in their profile (Michael Oct 12)
@MichaelN11 

Also, I don't see John and Jalen's tasks. Do you have other epics that I should read?
@JalenDmarion @JohnOwens19

**Comment by Vanasbry000** [comment]
@sjiang1 
Those are being made as we speak 👍
