### ISSUE TITLE
Expand/modify meal logs

### ISSUE THREAD

**Issue by Tsion-Tadesse** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#74]
**Subtasks:**
- [x] Record meals -(Tsion Oct 12)     
    - [x] create a form to input meals
    - [x] convert the user input to lowercase(to avoid case sensitivity issue)
- [x]  Modify the page to make it user friendly - (Tsion Oct 12)
    - [x] work on display (CSS of the meal log page)

**Test cases:**
- [x] make the program avoid invalid input

**Comment by sjiang1** [comment]
Is it going to be on the admin page or on the website for the user?
Example test cases for the task should be: 
- user can input meals by entering xxx in your form (I am not sure if it's accurate for your task)
- all the user inputs can converted to lowercase which will be sent to the database (?)

For the task of making it more user friendly: how will I know that you accomplish the task?

**Comment by Tsion-Tadesse** [comment]
It's going to be on the website for the user. 
For the task of making it more user friendly: how will I know that you accomplish the task? I meant to say making it easier for the user to put their input in, more of the CSS, I am going to remove it that

**Comment by Tsion-Tadesse** [comment]
make the program avoid invalid input by making the meal log input box performs like search bar. 
Note: previously convert the user input to lowercase(to avoid case sensitivity issue) was the plan, but avoiding invalid input can be difficult. Therefore, I have changed my approach to users to search for food to input rather than type(to avoid typo and unlisted food log).
