### ISSUE TITLE
Add dietary preferences/allergies to profile

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#77]
**Subtasks:**
- [x] Make allergy model 
    - [x] Many to many relationship with user
    - [x] Name field
    - [x] Description field
- [x] Make dietary preference model 
    - [x] Many to many relationship with user
    - [x] Name field
    - [x] Description field
- [x] Allow user to add allergies and dietary preferences to their account
    - [x] Add allergy/dietary preference page
    - [x] Dropdown to add allergy
    - [x] Dropdown to add dietary preferences
- [x] Display allergies and dietary preferences on profile page
    - [x] List of allergies
    - [x] List of dietary preferences

**Test Cases:**
- [x] User can add allergies and dietary preferences to their profile
- [x] Allergies and dietary preferences display as list on profile
