### ISSUE TITLE
Epic 3: User Profile, Daily Logs, and Recipes (cont.)

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#86]
As a user, I want to log my daily meals so that I can track my food consumption. I also want to build my own recipes and search for others so that I can diversify my eating habits, while being mindful of my food allergies and diet.

- [x] Recipes
   - [x] Recipe search (Jalen - Oct 19) #91 
   - [x] Recipe maker (Bryce - Oct 19) #87 
- [x] Profiles
   - [x] Fixing the profile update page (Bryce - Oct 19) #93 
   - [x] Making the profiles autogenerate alongside users (Michael - Oct 19) #92
- [x] Daily logs (Athena and Tsion - Oct 19) #89
- [x] Allergies/Diet Preferences (Michael - Oct 19) #88 
- [x] Add foods from USDA to our database (John) #37
