### ISSUE TITLE
Finish Allergies/Diet Preferences

### ISSUE THREAD

**Issue by ghost** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#88]
**Subtasks:**
- [x] User interface
    - [x] Delete allergy/diet preference from user
    - [x] When adding allergies/diet preferences, only display what the user doesn't already have
- [x] Database
    - [x] One-to-one relation to Profile instead of User
    - [x] Add more allergies/diet preferences to database

**Test Cases:**
- [x] User can delete allergies/diet preferences from their profile
- [x] User only sees allergies/diet preferences on the add list that they don't already have
- [x] More allergies/diet preferences to choose from on the list
