### ISSUE TITLE
Daily logs: connect front and back end

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#89]
**Subtasks**
- [x] Daily log page only accessible to logged in users
- [x] User can submit information for one meal at a time (meal log)
    - [x] Fields:
        - [x] Date
        - [x] Time
        - [x] Dynamically add (JavaScript needed):
            - [x] Food (drop-down list)
            - [x] Portions of that food (how many serving sizes)
    - [x] Information is saved to database
        - [x] If this is the first meal log for a particular day, a new daily log is created
- [x] After meal information is submitted:
    - [x] Display the date of the last daily log submitted 
 

**Test cases**
- [x] Logged in user can successfully submit their meal
- [x] Submitted information in the database will be viewable from admin page
