### ISSUE TITLE
Profile autogenerates upon user registration

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#92]
**Sub-tasks**
- [x] Create Profile objects tied to a User in the database whenever a User is created

**Test cases**
- [x] After a user registers, their profile instance will be visible from the admin page
- [x] The profile page will work
